version: '3.8'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: solver_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: budget_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app 
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend 
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
