"""Initial schema

Revision ID: faa4ed50b1c1
Revises: 
Create Date: 2025-10-04 17:52:54.896657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa4ed50b1c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_project_sets_name', table_name='project_sets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_project_sets_name', 'project_sets', ['name'], unique=False)
    # ### end Alembic commands ###
