version: '3.8'
services:
  app:
    build: ./python
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./python:/app
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: budget
    ports:
      - "5432:5432"
